# Generated by Django 4.1.3 on 2023-01-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercrd',
            fields=[
                ('email', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('confirmpassword', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Sports',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
