# Generated by Django 4.1.3 on 2023-01-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_usercrd_delete_sports_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercrd',
            old_name='password',
            new_name='pswd',
        ),
    ]
