# Generated by Django 4.1.3 on 2023-02-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_rename_password_usercrd_pswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=30)),
                ('imagePath', models.ImageField(upload_to='notes/')),
            ],
        ),
    ]
