# Generated by Django 4.1.3 on 2023-02-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0006_usercontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='num',
            new_name='number',
        ),
    ]
