# Generated by Django 4.1.3 on 2023-02-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0007_rename_num_usercontact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='course',
            new_name='user_course',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='number',
            new_name='user_number',
        ),
    ]
